// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: proto/cluster/cluster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PartitionMigrator_StreamJobs_FullMethodName = "/proto.PartitionMigrator/StreamJobs"
)

// PartitionMigratorClient is the client API for PartitionMigrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionMigratorClient interface {
	// Bidirectional streaming RPC for migrating jobs in batches
	StreamJobs(ctx context.Context, opts ...grpc.CallOption) (PartitionMigrator_StreamJobsClient, error)
}

type partitionMigratorClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionMigratorClient(cc grpc.ClientConnInterface) PartitionMigratorClient {
	return &partitionMigratorClient{cc}
}

func (c *partitionMigratorClient) StreamJobs(ctx context.Context, opts ...grpc.CallOption) (PartitionMigrator_StreamJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PartitionMigrator_ServiceDesc.Streams[0], PartitionMigrator_StreamJobs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &partitionMigratorStreamJobsClient{stream}
	return x, nil
}

type PartitionMigrator_StreamJobsClient interface {
	Send(*StreamJobsRequest) error
	Recv() (*JobsBatchAck, error)
	grpc.ClientStream
}

type partitionMigratorStreamJobsClient struct {
	grpc.ClientStream
}

func (x *partitionMigratorStreamJobsClient) Send(m *StreamJobsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *partitionMigratorStreamJobsClient) Recv() (*JobsBatchAck, error) {
	m := new(JobsBatchAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PartitionMigratorServer is the server API for PartitionMigrator service.
// All implementations must embed UnimplementedPartitionMigratorServer
// for forward compatibility
type PartitionMigratorServer interface {
	// Bidirectional streaming RPC for migrating jobs in batches
	StreamJobs(PartitionMigrator_StreamJobsServer) error
	mustEmbedUnimplementedPartitionMigratorServer()
}

// UnimplementedPartitionMigratorServer must be embedded to have forward compatible implementations.
type UnimplementedPartitionMigratorServer struct {
}

func (UnimplementedPartitionMigratorServer) StreamJobs(PartitionMigrator_StreamJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedPartitionMigratorServer) mustEmbedUnimplementedPartitionMigratorServer() {}

// UnsafePartitionMigratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionMigratorServer will
// result in compilation errors.
type UnsafePartitionMigratorServer interface {
	mustEmbedUnimplementedPartitionMigratorServer()
}

func RegisterPartitionMigratorServer(s grpc.ServiceRegistrar, srv PartitionMigratorServer) {
	s.RegisterService(&PartitionMigrator_ServiceDesc, srv)
}

func _PartitionMigrator_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PartitionMigratorServer).StreamJobs(&partitionMigratorStreamJobsServer{stream})
}

type PartitionMigrator_StreamJobsServer interface {
	Send(*JobsBatchAck) error
	Recv() (*StreamJobsRequest, error)
	grpc.ServerStream
}

type partitionMigratorStreamJobsServer struct {
	grpc.ServerStream
}

func (x *partitionMigratorStreamJobsServer) Send(m *JobsBatchAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *partitionMigratorStreamJobsServer) Recv() (*StreamJobsRequest, error) {
	m := new(StreamJobsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PartitionMigrator_ServiceDesc is the grpc.ServiceDesc for PartitionMigrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionMigrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PartitionMigrator",
	HandlerType: (*PartitionMigratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _PartitionMigrator_StreamJobs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/cluster/cluster.proto",
}
